[package]
name = "Bevy_Basics_Remastered"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
rand = "*"

[profile.dev.package."*"]
opt-level = 3

[[example]]
name = "ball fps"
path = "examples/ball_fps"
doc-scrape-examples = true